# Project: ASM_Test_C_Question_3
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main_03.o
LINKOBJ  = main_03.o
LIBS     = -L"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/lib" -L"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/include" -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/include" -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"F:/Main/University/App/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ASM_Test_C_Question_3.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = F:\Main\University\App\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main_03.o: main_03.c
	$(CC) -c main_03.c -o main_03.o $(CFLAGS)
